[project]
name = "webapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nicegui>=2.2.0",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.8",
]
